export const add_todo= "add_todo"
export const toggle_todo= "toggle_todo"
export const remove_todo= "remove_todo"
export const mark_completed= "mark_completed"
export const mark_incomplete= "mark_incomplete"
export const filter_todos= "filter_todos"
export const mark_all_completed= "mark_all_completed"
export const update_search_term= "update_search_term"